import Navbar from "@/components/landing/Navbar"
import Link from "next/link"

const Terms = () => {
  return (
    <main className="flex flex-col items-center min-h-screen w-full">
      <Navbar />
      <h1 className="text-3xl font-bold mb-6 text-gray-900">Terms of Service</h1>
      <div className="w-full max-w-7xl mx-auto p-4 mb-24">
        <strong>Last Updated: 06-23-2024</strong>
        <p>
          This Terms of Service agreement ("Terms") governs your use of Flycatcher ("we," "us," or "our") including our services
          and our website,{" "}
          <Link href="https://flycatcher.app/" className="text-blue-500 underline">
            https://flycatcher.app/
          </Link>{" "}
          ("Website"). By using our services or Website, you agree to the terms of this agreement. These Terms are governed in the
          United States under Texas law.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-4 text-gray-800">1. Our Services</h2>
        <p>Flycatcher is a suite of tools for users to collect feedback and analytics from their audiences.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-4 text-gray-800">2. Paid Subscriptions and Payment Information</h2>
        <p>
          If you decide to purchase a paid subscription, we will collect payment information to process the transaction. Paid
          subscriptions provide access to additional features and higher limits on usage of our services. Payments are processed
          securely by our trusted third-party payment processor, Stripe, and we do not store your payment information on our
          servers.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-4 text-gray-800">3. Additional Data Collection and Privacy</h2>
        <p>
          We collect and store user data, including email and payment information, to provide our services. Please refer to our
          Privacy Policy at{" "}
          <Link href="https://flycatcher.app/privacy" className="text-blue-500 underline">
            https://flycatcher.app/privacy
          </Link>{" "}
          for additional information about how we use your data. Additionally, we collect non-personal data for basic analytics
          and to track interest in our services. We do not use cookies.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-4 text-gray-800">4. Usage Rights</h2>
        <p>
          When you create a feedback board on Flycatcher, the content generated by your users on the feedback board is owned by
          you. However, you do not have the right to resell the feedback board service itself.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-4 text-gray-800">5. Updates and Contact</h2>
        <p>
          Updates to these Terms will be reflected on this page, major changes may be communicated to the email associated with
          your account. For any questions or concerns, please contact us at flycatcherapp@gmail.com
        </p>
      </div>
    </main>
  )
}

export default Terms
